package advent.year2025.day7

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class TachyonManifoldTest {

  @Test
  fun `numSplits -- reference example -- 21`() {
    val input = """
     .......S.......
     ...............
     .......^.......
     ...............
     ......^.^......
     ...............
     .....^.^.^.....
     ...............
     ....^.^...^....
     ...............
     ...^.^...^.^...
     ...............
     ..^...^.....^..
     ...............
     .^.^.^.^.^...^.
     ...............
   """.trimIndent()
    val manifold = TachyonManifold.of(input)

    val numSplits = manifold.finalBeams().numSplits

    assertThat(numSplits).isEqualTo(21)
  }

  @Test
  fun `numTimelines -- reference example -- 40`() {
    val input = """
     .......S.......
     ...............
     .......^.......
     ...............
     ......^.^......
     ...............
     .....^.^.^.....
     ...............
     ....^.^...^....
     ...............
     ...^.^...^.^...
     ...............
     ..^...^.....^..
     ...............
     .^.^.^.^.^...^.
     ...............
   """.trimIndent()
    val manifold = TachyonManifold.of(input)

    val numTimelines = manifold.finalBeams().numTimelines()

    assertThat(numTimelines).isEqualTo(40L)
  }
}